import type { Hero } from '../../src/data/heroTypes.js';
import { uniqueStrings } from './normalize.js';

const SAFE_OVERRIDE_FIELDS = ['englishName', 'chineseName', 'imageLink', 'artLink', 'artPosition', 'occupation', 'altOccupation', 'aliases', 'campId', 'releaseDate', 'officialPickRate', 'officialPickRateUpdatedAt'] as const;

export type HeroOverride = Pick<Partial<Hero>, typeof SAFE_OVERRIDE_FIELDS[number]>;

export function mergeOverride(current: HeroOverride | undefined, next: HeroOverride): HeroOverride {
  const result: HeroOverride = { ...(current || {}) };
  for (const key of SAFE_OVERRIDE_FIELDS) {
    if (next[key] !== undefined) {
      (result as Record<string, unknown>)[key] = next[key];
    }
  }
  if (current?.aliases || next.aliases) result.aliases = uniqueStrings([...(current?.aliases || []), ...(next.aliases || [])]);
  return result;
}

function stableObject(value: unknown) {
  return JSON.stringify(value, null, 2);
}

export function renderAutoSyncedHeroes(heroes: Hero[]) {
  return `import type { Hero } from './heroTypes.js';

//
// AUTO-GENERATED by scripts/hero-sync/sync.ts.
// Review the generated PR; do not edit relationship data here.
//
const autoSyncedHeroes: Hero[] = ${stableObject(heroes)};

export default autoSyncedHeroes;
`;
}

export function renderOverrides(overrides: Record<number, HeroOverride>) {
  const ordered = Object.fromEntries(Object.entries(overrides).sort((a, b) => Number(a[0]) - Number(b[0])));
  return `import type { Hero } from './heroTypes.js';

//
// AUTO-GENERATED by scripts/hero-sync/sync.ts.
// Relationship fields are intentionally excluded.
//
const heroSyncOverrides: Record<number, Partial<Hero>> = ${stableObject(ordered)};

export default heroSyncOverrides;
`;
}
