// Riot Data Dragon 16.19.1; generated by scripts/lol-sync.mjs.
import type { Hero } from './heroTypes.js';
const heroes: Hero[] = [
  {
    "id": 1,
    "englishName": "Annie",
    "chineseName": "安妮",
    "imageLink": "/champions/Annie.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Annie_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Annie",
      "the Dark Child",
      "黑暗之女"
    ]
  },
  {
    "id": 2,
    "englishName": "Olaf",
    "chineseName": "奥拉夫",
    "imageLink": "/champions/Olaf.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Olaf_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Olaf",
      "the Berserker",
      "狂战士"
    ]
  },
  {
    "id": 3,
    "englishName": "Galio",
    "chineseName": "加里奥",
    "imageLink": "/champions/Galio.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Galio_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Galio",
      "the Colossus",
      "正义巨像"
    ]
  },
  {
    "id": 4,
    "englishName": "Twisted Fate",
    "chineseName": "崔斯特",
    "imageLink": "/champions/TwistedFate.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/TwistedFate_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "TwistedFate",
      "the Card Master",
      "卡牌大师"
    ]
  },
  {
    "id": 5,
    "englishName": "Xin Zhao",
    "chineseName": "赵信",
    "imageLink": "/champions/XinZhao.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/XinZhao_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "XinZhao",
      "the Seneschal of Demacia",
      "德邦总管"
    ]
  },
  {
    "id": 6,
    "englishName": "Urgot",
    "chineseName": "厄加特",
    "imageLink": "/champions/Urgot.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Urgot_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Urgot",
      "the Dreadnought",
      "无畏战车"
    ]
  },
  {
    "id": 7,
    "englishName": "LeBlanc",
    "chineseName": "乐芙兰",
    "imageLink": "/champions/Leblanc.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leblanc_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Leblanc",
      "the Deceiver",
      "诡术妖姬"
    ]
  },
  {
    "id": 8,
    "englishName": "Vladimir",
    "chineseName": "弗拉基米尔",
    "imageLink": "/champions/Vladimir.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vladimir_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Vladimir",
      "the Crimson Reaper",
      "猩红收割者"
    ]
  },
  {
    "id": 9,
    "englishName": "Fiddlesticks",
    "chineseName": "费德提克",
    "imageLink": "/champions/Fiddlesticks.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiddlesticks_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Fiddlesticks",
      "the Ancient Fear",
      "远古恐惧"
    ]
  },
  {
    "id": 10,
    "englishName": "Kayle",
    "chineseName": "凯尔",
    "imageLink": "/champions/Kayle.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayle_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Kayle",
      "the Righteous",
      "正义天使"
    ]
  },
  {
    "id": 11,
    "englishName": "Master Yi",
    "chineseName": "易",
    "imageLink": "/champions/MasterYi.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MasterYi_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "MasterYi",
      "the Wuju Bladesman",
      "无极剑圣"
    ]
  },
  {
    "id": 12,
    "englishName": "Alistar",
    "chineseName": "阿利斯塔",
    "imageLink": "/champions/Alistar.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Alistar_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Alistar",
      "the Minotaur",
      "牛头酋长"
    ]
  },
  {
    "id": 13,
    "englishName": "Ryze",
    "chineseName": "瑞兹",
    "imageLink": "/champions/Ryze.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ryze_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Ryze",
      "the Rune Mage",
      "符文法师"
    ]
  },
  {
    "id": 14,
    "englishName": "Sion",
    "chineseName": "赛恩",
    "imageLink": "/champions/Sion.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sion_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Sion",
      "The Undead Juggernaut",
      "亡灵战神"
    ]
  },
  {
    "id": 15,
    "englishName": "Sivir",
    "chineseName": "希维尔",
    "imageLink": "/champions/Sivir.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sivir_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Sivir",
      "the Battle Mistress",
      "战争女神"
    ]
  },
  {
    "id": 16,
    "englishName": "Soraka",
    "chineseName": "索拉卡",
    "imageLink": "/champions/Soraka.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Soraka_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Soraka",
      "the Starchild",
      "众星之子"
    ]
  },
  {
    "id": 17,
    "englishName": "Teemo",
    "chineseName": "提莫",
    "imageLink": "/champions/Teemo.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Teemo_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Teemo",
      "the Swift Scout",
      "迅捷斥候"
    ]
  },
  {
    "id": 18,
    "englishName": "Tristana",
    "chineseName": "崔丝塔娜",
    "imageLink": "/champions/Tristana.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tristana_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Tristana",
      "the Yordle Gunner",
      "麦林炮手"
    ]
  },
  {
    "id": 19,
    "englishName": "Warwick",
    "chineseName": "沃里克",
    "imageLink": "/champions/Warwick.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Warwick_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Warwick",
      "the Uncaged Wrath of Zaun",
      "祖安怒兽"
    ]
  },
  {
    "id": 20,
    "englishName": "Nunu & Willump",
    "chineseName": "努努和威朗普",
    "imageLink": "/champions/Nunu.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nunu_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Nunu",
      "the Boy and His Yeti",
      "雪原双子"
    ]
  },
  {
    "id": 21,
    "englishName": "Miss Fortune",
    "chineseName": "厄运小姐",
    "imageLink": "/champions/MissFortune.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MissFortune_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "MissFortune",
      "the Bounty Hunter",
      "赏金猎人"
    ]
  },
  {
    "id": 22,
    "englishName": "Ashe",
    "chineseName": "艾希",
    "imageLink": "/champions/Ashe.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ashe_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Ashe",
      "the Frost Archer",
      "寒冰射手"
    ]
  },
  {
    "id": 23,
    "englishName": "Tryndamere",
    "chineseName": "泰达米尔",
    "imageLink": "/champions/Tryndamere.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Tryndamere_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Tryndamere",
      "the Barbarian King",
      "蛮族之王"
    ]
  },
  {
    "id": 24,
    "englishName": "Jax",
    "chineseName": "贾克斯",
    "imageLink": "/champions/Jax.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jax_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Jax",
      "Grandmaster at Arms",
      "武器大师"
    ]
  },
  {
    "id": 25,
    "englishName": "Morgana",
    "chineseName": "莫甘娜",
    "imageLink": "/champions/Morgana.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Morgana_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Morgana",
      "the Fallen",
      "堕落天使"
    ]
  },
  {
    "id": 26,
    "englishName": "Zilean",
    "chineseName": "基兰",
    "imageLink": "/champions/Zilean.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zilean_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Zilean",
      "the Chronokeeper",
      "时光守护者"
    ]
  },
  {
    "id": 27,
    "englishName": "Singed",
    "chineseName": "辛吉德",
    "imageLink": "/champions/Singed.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Singed_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Singed",
      "the Mad Chemist",
      "炼金术士"
    ]
  },
  {
    "id": 28,
    "englishName": "Evelynn",
    "chineseName": "伊芙琳",
    "imageLink": "/champions/Evelynn.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Evelynn_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Evelynn",
      "Agony's Embrace",
      "痛苦之拥"
    ]
  },
  {
    "id": 29,
    "englishName": "Twitch",
    "chineseName": "图奇",
    "imageLink": "/champions/Twitch.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Twitch_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Twitch",
      "the Plague Rat",
      "瘟疫之源"
    ]
  },
  {
    "id": 30,
    "englishName": "Karthus",
    "chineseName": "卡尔萨斯",
    "imageLink": "/champions/Karthus.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karthus_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Karthus",
      "the Deathsinger",
      "死亡颂唱者"
    ]
  },
  {
    "id": 31,
    "englishName": "Cho'Gath",
    "chineseName": "科加斯",
    "imageLink": "/champions/Chogath.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Chogath_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Chogath",
      "the Terror of the Void",
      "虚空恐惧"
    ]
  },
  {
    "id": 32,
    "englishName": "Amumu",
    "chineseName": "阿木木",
    "imageLink": "/champions/Amumu.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Amumu_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Amumu",
      "the Sad Mummy",
      "殇之木乃伊"
    ]
  },
  {
    "id": 33,
    "englishName": "Rammus",
    "chineseName": "拉莫斯",
    "imageLink": "/champions/Rammus.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rammus_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Rammus",
      "the Armordillo",
      "披甲龙龟"
    ]
  },
  {
    "id": 34,
    "englishName": "Anivia",
    "chineseName": "艾尼维亚",
    "imageLink": "/champions/Anivia.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Anivia_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Anivia",
      "the Cryophoenix",
      "冰晶凤凰"
    ]
  },
  {
    "id": 35,
    "englishName": "Shaco",
    "chineseName": "萨科",
    "imageLink": "/champions/Shaco.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shaco_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Shaco",
      "the Demon Jester",
      "恶魔小丑"
    ]
  },
  {
    "id": 36,
    "englishName": "Dr. Mundo",
    "chineseName": "蒙多医生",
    "imageLink": "/champions/DrMundo.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/DrMundo_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "DrMundo",
      "the Madman of Zaun",
      "祖安狂人"
    ]
  },
  {
    "id": 37,
    "englishName": "Sona",
    "chineseName": "娑娜",
    "imageLink": "/champions/Sona.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sona_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Sona",
      "Maven of the Strings",
      "琴瑟仙女"
    ]
  },
  {
    "id": 38,
    "englishName": "Kassadin",
    "chineseName": "卡萨丁",
    "imageLink": "/champions/Kassadin.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kassadin_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Kassadin",
      "the Void Walker",
      "虚空行者"
    ]
  },
  {
    "id": 39,
    "englishName": "Irelia",
    "chineseName": "艾瑞莉娅",
    "imageLink": "/champions/Irelia.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Irelia_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Irelia",
      "the Blade Dancer",
      "刀锋舞者"
    ]
  },
  {
    "id": 40,
    "englishName": "Janna",
    "chineseName": "迦娜",
    "imageLink": "/champions/Janna.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Janna_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Janna",
      "the Storm's Fury",
      "风暴之怒"
    ]
  },
  {
    "id": 41,
    "englishName": "Gangplank",
    "chineseName": "普朗克",
    "imageLink": "/champions/Gangplank.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gangplank_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Gangplank",
      "the Saltwater Scourge",
      "海洋之灾"
    ]
  },
  {
    "id": 42,
    "englishName": "Corki",
    "chineseName": "库奇",
    "imageLink": "/champions/Corki.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Corki_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Corki",
      "the Daring Bombardier",
      "英勇投弹手"
    ]
  },
  {
    "id": 43,
    "englishName": "Karma",
    "chineseName": "卡尔玛",
    "imageLink": "/champions/Karma.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Karma_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Karma",
      "the Enlightened One",
      "天启者"
    ]
  },
  {
    "id": 44,
    "englishName": "Taric",
    "chineseName": "塔里克",
    "imageLink": "/champions/Taric.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taric_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Taric",
      "the Shield of Valoran",
      "瓦洛兰之盾"
    ]
  },
  {
    "id": 45,
    "englishName": "Veigar",
    "chineseName": "维迦",
    "imageLink": "/champions/Veigar.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Veigar_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Veigar",
      "the Tiny Master of Evil",
      "邪恶小法师"
    ]
  },
  {
    "id": 48,
    "englishName": "Trundle",
    "chineseName": "特朗德尔",
    "imageLink": "/champions/Trundle.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Trundle_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Trundle",
      "the Troll King",
      "巨魔之王"
    ]
  },
  {
    "id": 50,
    "englishName": "Swain",
    "chineseName": "斯维因",
    "imageLink": "/champions/Swain.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Swain_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Swain",
      "the Noxian Grand General",
      "诺克萨斯统领"
    ]
  },
  {
    "id": 51,
    "englishName": "Caitlyn",
    "chineseName": "凯特琳",
    "imageLink": "/champions/Caitlyn.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Caitlyn_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Caitlyn",
      "the Sheriff of Piltover",
      "皮城女警"
    ]
  },
  {
    "id": 53,
    "englishName": "Blitzcrank",
    "chineseName": "布里茨",
    "imageLink": "/champions/Blitzcrank.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Blitzcrank_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Blitzcrank",
      "the Great Steam Golem",
      "蒸汽机器人"
    ]
  },
  {
    "id": 54,
    "englishName": "Malphite",
    "chineseName": "墨菲特",
    "imageLink": "/champions/Malphite.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malphite_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Malphite",
      "Shard of the Monolith",
      "熔岩巨兽"
    ]
  },
  {
    "id": 55,
    "englishName": "Katarina",
    "chineseName": "卡特琳娜",
    "imageLink": "/champions/Katarina.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Katarina_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Katarina",
      "the Sinister Blade",
      "不祥之刃"
    ]
  },
  {
    "id": 56,
    "englishName": "Nocturne",
    "chineseName": "魔腾",
    "imageLink": "/champions/Nocturne.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nocturne_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Nocturne",
      "the Eternal Nightmare",
      "永恒梦魇"
    ]
  },
  {
    "id": 57,
    "englishName": "Maokai",
    "chineseName": "茂凯",
    "imageLink": "/champions/Maokai.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Maokai_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Maokai",
      "the Twisted Treant",
      "扭曲树精"
    ]
  },
  {
    "id": 58,
    "englishName": "Renekton",
    "chineseName": "雷克顿",
    "imageLink": "/champions/Renekton.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renekton_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Renekton",
      "the Butcher of the Sands",
      "荒漠屠夫"
    ]
  },
  {
    "id": 59,
    "englishName": "Jarvan IV",
    "chineseName": "嘉文四世",
    "imageLink": "/champions/JarvanIV.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/JarvanIV_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "JarvanIV",
      "the Exemplar of Demacia",
      "德玛西亚皇子"
    ]
  },
  {
    "id": 60,
    "englishName": "Elise",
    "chineseName": "伊莉丝",
    "imageLink": "/champions/Elise.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Elise_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Elise",
      "the Spider Queen",
      "蜘蛛女皇"
    ]
  },
  {
    "id": 61,
    "englishName": "Orianna",
    "chineseName": "奥莉安娜",
    "imageLink": "/champions/Orianna.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Orianna_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Orianna",
      "the Lady of Clockwork",
      "发条魔灵"
    ]
  },
  {
    "id": 62,
    "englishName": "Wukong",
    "chineseName": "孙悟空",
    "imageLink": "/champions/MonkeyKing.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/MonkeyKing_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "MonkeyKing",
      "the Monkey King",
      "齐天大圣"
    ]
  },
  {
    "id": 63,
    "englishName": "Brand",
    "chineseName": "布兰德",
    "imageLink": "/champions/Brand.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Brand_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Brand",
      "the Burning Vengeance",
      "复仇焰魂"
    ]
  },
  {
    "id": 64,
    "englishName": "Lee Sin",
    "chineseName": "李青",
    "imageLink": "/champions/LeeSin.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/LeeSin_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "LeeSin",
      "the Blind Monk",
      "盲僧"
    ]
  },
  {
    "id": 67,
    "englishName": "Vayne",
    "chineseName": "薇恩",
    "imageLink": "/champions/Vayne.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vayne_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Vayne",
      "the Night Hunter",
      "暗夜猎手"
    ]
  },
  {
    "id": 68,
    "englishName": "Rumble",
    "chineseName": "兰博",
    "imageLink": "/champions/Rumble.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rumble_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Rumble",
      "the Mechanized Menace",
      "机械公敌"
    ]
  },
  {
    "id": 69,
    "englishName": "Cassiopeia",
    "chineseName": "卡西奥佩娅",
    "imageLink": "/champions/Cassiopeia.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Cassiopeia_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Cassiopeia",
      "the Serpent's Embrace",
      "魔蛇之拥"
    ]
  },
  {
    "id": 72,
    "englishName": "Skarner",
    "chineseName": "斯卡纳",
    "imageLink": "/champions/Skarner.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Skarner_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Skarner",
      "the Primordial Sovereign",
      "上古领主"
    ]
  },
  {
    "id": 74,
    "englishName": "Heimerdinger",
    "chineseName": "黑默丁格",
    "imageLink": "/champions/Heimerdinger.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Heimerdinger_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Heimerdinger",
      "the Revered Inventor",
      "大发明家"
    ]
  },
  {
    "id": 75,
    "englishName": "Nasus",
    "chineseName": "内瑟斯",
    "imageLink": "/champions/Nasus.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nasus_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Nasus",
      "the Curator of the Sands",
      "沙漠死神"
    ]
  },
  {
    "id": 76,
    "englishName": "Nidalee",
    "chineseName": "奈德丽",
    "imageLink": "/champions/Nidalee.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nidalee_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Nidalee",
      "the Bestial Huntress",
      "狂野女猎手"
    ]
  },
  {
    "id": 77,
    "englishName": "Udyr",
    "chineseName": "乌迪尔",
    "imageLink": "/champions/Udyr.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Udyr_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Udyr",
      "the Spirit Walker",
      "兽灵行者"
    ]
  },
  {
    "id": 78,
    "englishName": "Poppy",
    "chineseName": "波比",
    "imageLink": "/champions/Poppy.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Poppy",
      "Keeper of the Hammer",
      "圣锤之毅"
    ]
  },
  {
    "id": 79,
    "englishName": "Gragas",
    "chineseName": "古拉加斯",
    "imageLink": "/champions/Gragas.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gragas_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Gragas",
      "the Rabble Rouser",
      "酒桶"
    ]
  },
  {
    "id": 80,
    "englishName": "Pantheon",
    "chineseName": "潘森",
    "imageLink": "/champions/Pantheon.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pantheon_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Pantheon",
      "the Unbreakable Spear",
      "不屈之枪"
    ]
  },
  {
    "id": 81,
    "englishName": "Ezreal",
    "chineseName": "伊泽瑞尔",
    "imageLink": "/champions/Ezreal.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ezreal_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Ezreal",
      "the Prodigal Explorer",
      "探险家"
    ]
  },
  {
    "id": 82,
    "englishName": "Mordekaiser",
    "chineseName": "莫德凯撒",
    "imageLink": "/champions/Mordekaiser.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mordekaiser_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Mordekaiser",
      "the Iron Revenant",
      "铁铠冥魂"
    ]
  },
  {
    "id": 83,
    "englishName": "Yorick",
    "chineseName": "约里克",
    "imageLink": "/champions/Yorick.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yorick_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Yorick",
      "Shepherd of Souls",
      "牧魂人"
    ]
  },
  {
    "id": 84,
    "englishName": "Akali",
    "chineseName": "阿卡丽",
    "imageLink": "/champions/Akali.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akali_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Akali",
      "the Rogue Assassin",
      "离群之刺"
    ]
  },
  {
    "id": 85,
    "englishName": "Kennen",
    "chineseName": "凯南",
    "imageLink": "/champions/Kennen.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kennen_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Kennen",
      "the Heart of the Tempest",
      "狂暴之心"
    ]
  },
  {
    "id": 86,
    "englishName": "Garen",
    "chineseName": "盖伦",
    "imageLink": "/champions/Garen.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Garen_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Garen",
      "The Might of Demacia",
      "德玛西亚之力"
    ]
  },
  {
    "id": 89,
    "englishName": "Leona",
    "chineseName": "蕾欧娜",
    "imageLink": "/champions/Leona.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Leona_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Leona",
      "the Radiant Dawn",
      "曙光女神"
    ]
  },
  {
    "id": 90,
    "englishName": "Malzahar",
    "chineseName": "玛尔扎哈",
    "imageLink": "/champions/Malzahar.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Malzahar_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Malzahar",
      "the Prophet of the Void",
      "虚空先知"
    ]
  },
  {
    "id": 91,
    "englishName": "Talon",
    "chineseName": "泰隆",
    "imageLink": "/champions/Talon.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Talon_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Talon",
      "the Blade's Shadow",
      "刀锋之影"
    ]
  },
  {
    "id": 92,
    "englishName": "Riven",
    "chineseName": "锐雯",
    "imageLink": "/champions/Riven.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Riven_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Riven",
      "the Exile",
      "放逐之刃"
    ]
  },
  {
    "id": 96,
    "englishName": "Kog'Maw",
    "chineseName": "克格莫",
    "imageLink": "/champions/KogMaw.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/KogMaw_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "KogMaw",
      "the Mouth of the Abyss",
      "深渊巨口"
    ]
  },
  {
    "id": 98,
    "englishName": "Shen",
    "chineseName": "慎",
    "imageLink": "/champions/Shen.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shen_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Shen",
      "the Eye of Twilight",
      "暮光之眼"
    ]
  },
  {
    "id": 99,
    "englishName": "Lux",
    "chineseName": "拉克丝",
    "imageLink": "/champions/Lux.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lux_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Lux",
      "the Lady of Luminosity",
      "光辉女郎"
    ]
  },
  {
    "id": 101,
    "englishName": "Xerath",
    "chineseName": "泽拉斯",
    "imageLink": "/champions/Xerath.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xerath_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Xerath",
      "the Magus Ascendant",
      "远古巫灵"
    ]
  },
  {
    "id": 102,
    "englishName": "Shyvana",
    "chineseName": "希瓦娜",
    "imageLink": "/champions/Shyvana.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Shyvana_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Shyvana",
      "the Half-Dragon",
      "龙血武姬"
    ]
  },
  {
    "id": 103,
    "englishName": "Ahri",
    "chineseName": "阿狸",
    "imageLink": "/champions/Ahri.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ahri_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Ahri",
      "the Nine-Tailed Fox",
      "九尾妖狐"
    ]
  },
  {
    "id": 104,
    "englishName": "Graves",
    "chineseName": "格雷福斯",
    "imageLink": "/champions/Graves.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Graves_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Graves",
      "the Outlaw",
      "法外狂徒"
    ]
  },
  {
    "id": 105,
    "englishName": "Fizz",
    "chineseName": "菲兹",
    "imageLink": "/champions/Fizz.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fizz_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Fizz",
      "the Tidal Trickster",
      "潮汐海灵"
    ]
  },
  {
    "id": 106,
    "englishName": "Volibear",
    "chineseName": "沃利贝尔",
    "imageLink": "/champions/Volibear.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Volibear_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Volibear",
      "the Relentless Storm",
      "不灭狂雷"
    ]
  },
  {
    "id": 107,
    "englishName": "Rengar",
    "chineseName": "雷恩加尔",
    "imageLink": "/champions/Rengar.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rengar_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Rengar",
      "the Pridestalker",
      "傲之追猎者"
    ]
  },
  {
    "id": 110,
    "englishName": "Varus",
    "chineseName": "韦鲁斯",
    "imageLink": "/champions/Varus.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Varus_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Varus",
      "the Arrow of Retribution",
      "惩戒之箭"
    ]
  },
  {
    "id": 111,
    "englishName": "Nautilus",
    "chineseName": "诺提勒斯",
    "imageLink": "/champions/Nautilus.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nautilus_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Nautilus",
      "the Titan of the Depths",
      "深海泰坦"
    ]
  },
  {
    "id": 112,
    "englishName": "Viktor",
    "chineseName": "维克托",
    "imageLink": "/champions/Viktor.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viktor_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Viktor",
      "the Herald of the Arcane",
      "奥术先驱"
    ]
  },
  {
    "id": 113,
    "englishName": "Sejuani",
    "chineseName": "瑟庄妮",
    "imageLink": "/champions/Sejuani.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sejuani_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Sejuani",
      "Fury of the North",
      "北地之怒"
    ]
  },
  {
    "id": 114,
    "englishName": "Fiora",
    "chineseName": "菲奥娜",
    "imageLink": "/champions/Fiora.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Fiora_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Fiora",
      "the Grand Duelist",
      "无双剑姬"
    ]
  },
  {
    "id": 115,
    "englishName": "Ziggs",
    "chineseName": "吉格斯",
    "imageLink": "/champions/Ziggs.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ziggs_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Ziggs",
      "the Hexplosives Expert",
      "爆破鬼才"
    ]
  },
  {
    "id": 117,
    "englishName": "Lulu",
    "chineseName": "璐璐",
    "imageLink": "/champions/Lulu.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lulu_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Lulu",
      "the Fae Sorceress",
      "仙灵女巫"
    ]
  },
  {
    "id": 119,
    "englishName": "Draven",
    "chineseName": "德莱文",
    "imageLink": "/champions/Draven.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Draven_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Draven",
      "the Glorious Executioner",
      "荣耀行刑官"
    ]
  },
  {
    "id": 120,
    "englishName": "Hecarim",
    "chineseName": "赫卡里姆",
    "imageLink": "/champions/Hecarim.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Hecarim_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Hecarim",
      "the Shadow of War",
      "战争之影"
    ]
  },
  {
    "id": 121,
    "englishName": "Kha'Zix",
    "chineseName": "卡兹克",
    "imageLink": "/champions/Khazix.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Khazix_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Khazix",
      "the Voidreaver",
      "虚空掠夺者"
    ]
  },
  {
    "id": 122,
    "englishName": "Darius",
    "chineseName": "德莱厄斯",
    "imageLink": "/champions/Darius.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Darius_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Darius",
      "the Hand of Noxus",
      "诺克萨斯之手"
    ]
  },
  {
    "id": 126,
    "englishName": "Jayce",
    "chineseName": "杰斯",
    "imageLink": "/champions/Jayce.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jayce_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Jayce",
      "the Defender of Tomorrow",
      "未来守护者"
    ]
  },
  {
    "id": 127,
    "englishName": "Lissandra",
    "chineseName": "丽桑卓",
    "imageLink": "/champions/Lissandra.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lissandra_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Lissandra",
      "the Ice Witch",
      "冰霜女巫"
    ]
  },
  {
    "id": 131,
    "englishName": "Diana",
    "chineseName": "黛安娜",
    "imageLink": "/champions/Diana.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Diana_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Diana",
      "Scorn of the Moon",
      "皎月女神"
    ]
  },
  {
    "id": 133,
    "englishName": "Quinn",
    "chineseName": "奎因",
    "imageLink": "/champions/Quinn.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Quinn_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Quinn",
      "Demacia's Wings",
      "德玛西亚之翼"
    ]
  },
  {
    "id": 134,
    "englishName": "Syndra",
    "chineseName": "辛德拉",
    "imageLink": "/champions/Syndra.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Syndra_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Syndra",
      "the Dark Sovereign",
      "暗黑元首"
    ]
  },
  {
    "id": 136,
    "englishName": "Aurelion Sol",
    "chineseName": "奥瑞利安·索尔",
    "imageLink": "/champions/AurelionSol.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/AurelionSol_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "AurelionSol",
      "The Star Forger",
      "铸星龙王"
    ]
  },
  {
    "id": 141,
    "englishName": "Kayn",
    "chineseName": "凯隐",
    "imageLink": "/champions/Kayn.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kayn_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Kayn",
      "the Shadow Reaper",
      "影流之镰"
    ]
  },
  {
    "id": 142,
    "englishName": "Zoe",
    "chineseName": "佐伊",
    "imageLink": "/champions/Zoe.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zoe_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Zoe",
      "the Aspect of Twilight",
      "暮光星灵"
    ]
  },
  {
    "id": 143,
    "englishName": "Zyra",
    "chineseName": "婕拉",
    "imageLink": "/champions/Zyra.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zyra_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Zyra",
      "Rise of the Thorns",
      "荆棘之兴"
    ]
  },
  {
    "id": 145,
    "englishName": "Kai'Sa",
    "chineseName": "卡莎",
    "imageLink": "/champions/Kaisa.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kaisa_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Kaisa",
      "Daughter of the Void",
      "虚空之女"
    ]
  },
  {
    "id": 147,
    "englishName": "Seraphine",
    "chineseName": "萨勒芬妮",
    "imageLink": "/champions/Seraphine.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Seraphine_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Seraphine",
      "the Starry-Eyed Songstress",
      "星籁歌姬"
    ]
  },
  {
    "id": 150,
    "englishName": "Gnar",
    "chineseName": "纳尔",
    "imageLink": "/champions/Gnar.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gnar_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Gnar",
      "the Missing Link",
      "迷失之牙"
    ]
  },
  {
    "id": 154,
    "englishName": "Zac",
    "chineseName": "扎克",
    "imageLink": "/champions/Zac.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zac_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Zac",
      "the Secret Weapon",
      "生化魔人"
    ]
  },
  {
    "id": 157,
    "englishName": "Yasuo",
    "chineseName": "亚索",
    "imageLink": "/champions/Yasuo.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yasuo_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Yasuo",
      "the Unforgiven",
      "疾风剑豪"
    ]
  },
  {
    "id": 161,
    "englishName": "Vel'Koz",
    "chineseName": "维克兹",
    "imageLink": "/champions/Velkoz.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Velkoz_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Velkoz",
      "the Eye of the Void",
      "虚空之眼"
    ]
  },
  {
    "id": 163,
    "englishName": "Taliyah",
    "chineseName": "塔莉垭",
    "imageLink": "/champions/Taliyah.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Taliyah_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Taliyah",
      "the Stoneweaver",
      "岩雀"
    ]
  },
  {
    "id": 164,
    "englishName": "Camille",
    "chineseName": "卡蜜尔",
    "imageLink": "/champions/Camille.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Camille_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Camille",
      "the Steel Shadow",
      "青钢影"
    ]
  },
  {
    "id": 166,
    "englishName": "Akshan",
    "chineseName": "阿克尚",
    "imageLink": "/champions/Akshan.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Akshan_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Akshan",
      "the Rogue Sentinel",
      "影哨"
    ]
  },
  {
    "id": 200,
    "englishName": "Bel'Veth",
    "chineseName": "卑尔维斯",
    "imageLink": "/champions/Belveth.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Belveth_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Belveth",
      "the Empress of the Void",
      "虚空女皇"
    ]
  },
  {
    "id": 201,
    "englishName": "Braum",
    "chineseName": "布隆",
    "imageLink": "/champions/Braum.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Braum_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Braum",
      "the Heart of the Freljord",
      "弗雷尔卓德之心"
    ]
  },
  {
    "id": 202,
    "englishName": "Jhin",
    "chineseName": "烬",
    "imageLink": "/champions/Jhin.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jhin_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Jhin",
      "the Virtuoso",
      "戏命师"
    ]
  },
  {
    "id": 203,
    "englishName": "Kindred",
    "chineseName": "千珏",
    "imageLink": "/champions/Kindred.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kindred_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Kindred",
      "The Eternal Hunters",
      "永猎双子"
    ]
  },
  {
    "id": 221,
    "englishName": "Zeri",
    "chineseName": "泽丽",
    "imageLink": "/champions/Zeri.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zeri_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Zeri",
      "The Spark of Zaun",
      "祖安花火"
    ]
  },
  {
    "id": 222,
    "englishName": "Jinx",
    "chineseName": "金克丝",
    "imageLink": "/champions/Jinx.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Jinx_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Jinx",
      "the Loose Cannon",
      "暴走萝莉"
    ]
  },
  {
    "id": 223,
    "englishName": "Tahm Kench",
    "chineseName": "塔姆",
    "imageLink": "/champions/TahmKench.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/TahmKench_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "TahmKench",
      "The River King",
      "河流之王"
    ]
  },
  {
    "id": 233,
    "englishName": "Briar",
    "chineseName": "贝蕾亚",
    "imageLink": "/champions/Briar.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Briar_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Briar",
      "the Restrained Hunger",
      "狂厄蔷薇"
    ]
  },
  {
    "id": 234,
    "englishName": "Viego",
    "chineseName": "佛耶戈",
    "imageLink": "/champions/Viego.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Viego_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Viego",
      "The Ruined King",
      "破败之王"
    ]
  },
  {
    "id": 235,
    "englishName": "Senna",
    "chineseName": "赛娜",
    "imageLink": "/champions/Senna.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Senna_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Senna",
      "the Redeemer",
      "涤魂圣枪"
    ]
  },
  {
    "id": 236,
    "englishName": "Lucian",
    "chineseName": "卢锡安",
    "imageLink": "/champions/Lucian.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lucian_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Lucian",
      "the Purifier",
      "圣枪游侠"
    ]
  },
  {
    "id": 238,
    "englishName": "Zed",
    "chineseName": "劫",
    "imageLink": "/champions/Zed.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zed_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Zed",
      "the Master of Shadows",
      "影流之主"
    ]
  },
  {
    "id": 240,
    "englishName": "Kled",
    "chineseName": "克烈",
    "imageLink": "/champions/Kled.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kled_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Kled",
      "the Cantankerous Cavalier",
      "暴怒骑士"
    ]
  },
  {
    "id": 245,
    "englishName": "Ekko",
    "chineseName": "艾克",
    "imageLink": "/champions/Ekko.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ekko_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Ekko",
      "the Boy Who Shattered Time",
      "时间刺客"
    ]
  },
  {
    "id": 246,
    "englishName": "Qiyana",
    "chineseName": "奇亚娜",
    "imageLink": "/champions/Qiyana.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Qiyana_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Qiyana",
      "Empress of the Elements",
      "元素女皇"
    ]
  },
  {
    "id": 254,
    "englishName": "Vi",
    "chineseName": "蔚",
    "imageLink": "/champions/Vi.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vi_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Vi",
      "the Piltover Enforcer",
      "皮城执法官"
    ]
  },
  {
    "id": 266,
    "englishName": "Aatrox",
    "chineseName": "亚托克斯",
    "imageLink": "/champions/Aatrox.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aatrox_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Aatrox",
      "the Darkin Blade",
      "暗裔剑魔"
    ]
  },
  {
    "id": 267,
    "englishName": "Nami",
    "chineseName": "娜美",
    "imageLink": "/champions/Nami.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nami_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Nami",
      "the Tidecaller",
      "唤潮鲛姬"
    ]
  },
  {
    "id": 268,
    "englishName": "Azir",
    "chineseName": "阿兹尔",
    "imageLink": "/champions/Azir.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Azir_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Azir",
      "the Emperor of the Sands",
      "沙漠皇帝"
    ]
  },
  {
    "id": 350,
    "englishName": "Yuumi",
    "chineseName": "悠米",
    "imageLink": "/champions/Yuumi.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yuumi_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Yuumi",
      "the Magical Cat",
      "魔法猫咪"
    ]
  },
  {
    "id": 360,
    "englishName": "Samira",
    "chineseName": "莎弥拉",
    "imageLink": "/champions/Samira.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Samira_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Samira",
      "the Desert Rose",
      "沙漠玫瑰"
    ]
  },
  {
    "id": 412,
    "englishName": "Thresh",
    "chineseName": "锤石",
    "imageLink": "/champions/Thresh.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Thresh_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Thresh",
      "the Chain Warden",
      "魂锁典狱长"
    ]
  },
  {
    "id": 420,
    "englishName": "Illaoi",
    "chineseName": "俄洛伊",
    "imageLink": "/champions/Illaoi.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Illaoi_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Illaoi",
      "the Kraken Priestess",
      "海兽祭司"
    ]
  },
  {
    "id": 421,
    "englishName": "Rek'Sai",
    "chineseName": "雷克塞",
    "imageLink": "/champions/RekSai.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/RekSai_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "RekSai",
      "the Void Burrower",
      "虚空遁地兽"
    ]
  },
  {
    "id": 427,
    "englishName": "Ivern",
    "chineseName": "艾翁",
    "imageLink": "/champions/Ivern.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ivern_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Ivern",
      "the Green Father",
      "翠神"
    ]
  },
  {
    "id": 429,
    "englishName": "Kalista",
    "chineseName": "卡莉丝塔",
    "imageLink": "/champions/Kalista.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Kalista_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Kalista",
      "the Spear of Vengeance",
      "复仇之矛"
    ]
  },
  {
    "id": 432,
    "englishName": "Bard",
    "chineseName": "巴德",
    "imageLink": "/champions/Bard.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Bard_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Bard",
      "the Wandering Caretaker",
      "星界游神"
    ]
  },
  {
    "id": 497,
    "englishName": "Rakan",
    "chineseName": "洛",
    "imageLink": "/champions/Rakan.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rakan_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Rakan",
      "The Charmer",
      "幻翎"
    ]
  },
  {
    "id": 498,
    "englishName": "Xayah",
    "chineseName": "霞",
    "imageLink": "/champions/Xayah.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Xayah_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Xayah",
      "the Rebel",
      "逆羽"
    ]
  },
  {
    "id": 516,
    "englishName": "Ornn",
    "chineseName": "奥恩",
    "imageLink": "/champions/Ornn.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ornn_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Ornn",
      "The Fire below the Mountain",
      "山隐之焰"
    ]
  },
  {
    "id": 517,
    "englishName": "Sylas",
    "chineseName": "塞拉斯",
    "imageLink": "/champions/Sylas.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sylas_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Sylas",
      "the Unshackled",
      "解脱者"
    ]
  },
  {
    "id": 518,
    "englishName": "Neeko",
    "chineseName": "妮蔻",
    "imageLink": "/champions/Neeko.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Neeko_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Neeko",
      "the Curious Chameleon",
      "万花通灵"
    ]
  },
  {
    "id": 523,
    "englishName": "Aphelios",
    "chineseName": "厄斐琉斯",
    "imageLink": "/champions/Aphelios.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aphelios_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Aphelios",
      "the Weapon of the Faithful",
      "残月之肃"
    ]
  },
  {
    "id": 526,
    "englishName": "Rell",
    "chineseName": "芮尔",
    "imageLink": "/champions/Rell.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Rell_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Rell",
      "the Iron Maiden",
      "镕铁少女"
    ]
  },
  {
    "id": 555,
    "englishName": "Pyke",
    "chineseName": "派克",
    "imageLink": "/champions/Pyke.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Pyke_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Pyke",
      "the Bloodharbor Ripper",
      "血港鬼影"
    ]
  },
  {
    "id": 711,
    "englishName": "Vex",
    "chineseName": "薇古丝",
    "imageLink": "/champions/Vex.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Vex_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Vex",
      "the Gloomist",
      "愁云使者"
    ]
  },
  {
    "id": 777,
    "englishName": "Yone",
    "chineseName": "永恩",
    "imageLink": "/champions/Yone.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yone_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Yone",
      "the Unforgotten",
      "封魔剑魂"
    ]
  },
  {
    "id": 799,
    "englishName": "Ambessa",
    "chineseName": "安蓓萨",
    "imageLink": "/champions/Ambessa.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Ambessa_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Ambessa",
      "Matriarch of War",
      "铁血狼母"
    ]
  },
  {
    "id": 800,
    "englishName": "Mel",
    "chineseName": "梅尔",
    "imageLink": "/champions/Mel.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Mel_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Mel",
      "the Soul's Reflection",
      "流光镜影"
    ]
  },
  {
    "id": 804,
    "englishName": "Yunara",
    "chineseName": "芸阿娜",
    "imageLink": "/champions/Yunara.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Yunara_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Yunara",
      "the Unbroken Faith",
      "不破之誓"
    ]
  },
  {
    "id": 805,
    "englishName": "Locke",
    "chineseName": "洛克",
    "imageLink": "/champions/Locke.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Locke_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Locke",
      "the Ashen Exorcist",
      "灰烬驱魔人"
    ]
  },
  {
    "id": 875,
    "englishName": "Sett",
    "chineseName": "瑟提",
    "imageLink": "/champions/Sett.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Sett_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Sett",
      "the Boss",
      "腕豪"
    ]
  },
  {
    "id": 876,
    "englishName": "Lillia",
    "chineseName": "莉莉娅",
    "imageLink": "/champions/Lillia.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Lillia_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Lillia",
      "the Bashful Bloom",
      "含羞蓓蕾"
    ]
  },
  {
    "id": 887,
    "englishName": "Gwen",
    "chineseName": "格温",
    "imageLink": "/champions/Gwen.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Gwen_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Gwen",
      "The Hallowed Seamstress",
      "灵罗娃娃"
    ]
  },
  {
    "id": 888,
    "englishName": "Renata Glasc",
    "chineseName": "烈娜塔 · 戈拉斯克",
    "imageLink": "/champions/Renata.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Renata_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Renata",
      "the Chem-Baroness",
      "炼金男爵"
    ]
  },
  {
    "id": 893,
    "englishName": "Aurora",
    "chineseName": "阿萝拉",
    "imageLink": "/champions/Aurora.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Aurora_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Aurora",
      "the Witch Between Worlds",
      "双界灵兔"
    ]
  },
  {
    "id": 895,
    "englishName": "Nilah",
    "chineseName": "尼菈",
    "imageLink": "/champions/Nilah.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Nilah_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Nilah",
      "the Joy Unbound",
      "不羁之悦"
    ]
  },
  {
    "id": 897,
    "englishName": "K'Sante",
    "chineseName": "奎桑提",
    "imageLink": "/champions/KSante.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/KSante_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "KSante",
      "the Pride of Nazumah",
      "纳祖芒荣耀"
    ]
  },
  {
    "id": 901,
    "englishName": "Smolder",
    "chineseName": "斯莫德",
    "imageLink": "/champions/Smolder.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Smolder_0.jpg",
    "occupation": "Bot Lane",
    "altOccupation": "",
    "aliases": [
      "Smolder",
      "the Fiery Fledgling",
      "炽炎雏龙"
    ]
  },
  {
    "id": 902,
    "englishName": "Milio",
    "chineseName": "米利欧",
    "imageLink": "/champions/Milio.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Milio_0.jpg",
    "occupation": "Support",
    "altOccupation": "",
    "aliases": [
      "Milio",
      "The Gentle Flame",
      "明烛"
    ]
  },
  {
    "id": 904,
    "englishName": "Zaahen",
    "chineseName": "亚恒",
    "imageLink": "/champions/Zaahen.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Zaahen_0.jpg",
    "occupation": "Top Lane",
    "altOccupation": "",
    "aliases": [
      "Zaahen",
      "The Unsundered",
      "不落魔锋"
    ]
  },
  {
    "id": 910,
    "englishName": "Hwei",
    "chineseName": "彗",
    "imageLink": "/champions/Hwei.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Hwei_0.jpg",
    "occupation": "Mid Lane",
    "altOccupation": "",
    "aliases": [
      "Hwei",
      "the Visionary",
      "异画师"
    ]
  },
  {
    "id": 950,
    "englishName": "Naafiri",
    "chineseName": "纳亚菲利",
    "imageLink": "/champions/Naafiri.png",
    "artLink": "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/Naafiri_0.jpg",
    "occupation": "Jungle",
    "altOccupation": "",
    "aliases": [
      "Naafiri",
      "the Hound of a Hundred Bites",
      "百裂冥犬"
    ]
  }
];
export default heroes;
