import { test,expect } from '@playwright/test';
import { harness } from './harness';
import { initialState, type TeamPreset } from '../src/shared/types';
test('team library: create, edit, load, copy isolation, explicit update, delete and language',async ({page,request,baseURL}) => {
  const h=await harness(baseURL);
  const headers={Authorization:'Bearer e2e-control'};
  try {
    await h.send({type:'reset_match'});
    await h.send({type:'settings',settings:{...h.state(),language:'eng'}});
    const existing=await (await request.get('/api/team-presets',{headers})).json();
    for(const team of existing.teams) await request.delete('/api/team-presets/'+team.id,{headers});
    page.on('dialog',dialog=>dialog.accept());
    await page.goto('/control#token=e2e-control');
    await page.getByRole('button',{name:'Match settings',exact:true}).click();
    await page.getByRole('button',{name:'Manage saved teams',exact:true}).click();
    const manager=page.locator('.library-dialog');
    await expect(manager).toBeVisible();
    await manager.getByLabel('Team name',{exact:true}).fill('Alpha Library');
    await manager.getByLabel('Player 1',{exact:true}).fill('Alpha Player');
    await manager.getByLabel('Choose image',{exact:true}).first().setInputFiles('e2e/fixtures/player-test.png');
    await expect(manager.locator('.portrait-status').first()).toHaveText('Portrait loaded');
    await manager.getByRole('button',{name:'Add substitute',exact:true}).click();
    await manager.getByLabel('Substitute player ID',{exact:true}).fill('Temporary Sub');
    await manager.locator('.reserve-row').getByLabel('Choose image',{exact:true}).setInputFiles('e2e/fixtures/player-test.png');
    await expect(manager.locator('.reserve-row .portrait-status')).toHaveText('Portrait loaded');
    await manager.getByRole('button',{name:'Save team',exact:true}).click();
    await expect(manager.locator('.library-status')).toHaveText('Team saved');
    let teams:TeamPreset[]=(await (await request.get('/api/team-presets',{headers})).json()).teams;
    const id=teams[0].id,portrait=teams[0].playerPortraits[0];
    expect(teams[0].players[0]).toBe('Alpha Player');
    await manager.getByRole('button',{name:'Load into match · TEAM BLUE',exact:true}).click();
    await expect.poll(()=>h.state().blueTeam.id).toBe(id);
    await expect(manager).toHaveCount(0);
    const settings=page.locator('.settings-inline');
    const quick=settings.locator('.quick-substitution').first();
    await quick.getByLabel('Choose saved player',{exact:true}).selectOption({label:'Temporary Sub · Support · Substitute'});
    await quick.getByRole('button',{name:'Fill player details',exact:true}).click();
    await expect(settings.getByLabel('Player 1',{exact:true}).first()).toHaveValue('Temporary Sub');
    await settings.getByRole('button',{name:'Save settings',exact:true}).click();
    await expect.poll(()=>h.state().blueTeam.players[0]).toBe('Temporary Sub');
    teams=(await (await request.get('/api/team-presets',{headers})).json()).teams;
    expect(teams[0].players[0]).toBe('Alpha Player');
    await settings.getByRole('button',{name:'Update saved team',exact:true}).first().click();
    await expect(settings.locator('.library-status')).toHaveText('Team saved');
    teams=(await (await request.get('/api/team-presets',{headers})).json()).teams;
    expect(teams[0].players[0]).toBe('Temporary Sub');
    await settings.getByLabel('Choose saved team TEAM RED',{exact:true}).selectOption(id);
    await expect(settings.locator('.library-sides > div').nth(1).getByRole('button',{name:'Load into match',exact:true})).toBeDisabled();
    const beta=await (await request.post('/api/team-presets',{headers,data:{...initialState().redTeam,name:'Beta Library'}})).json();
    await settings.getByRole('button',{name:'Refresh library',exact:true}).click();
    await expect(settings.getByLabel('Choose saved team TEAM RED')).toContainText('Beta Library');
    await settings.getByLabel('Choose saved team TEAM RED').selectOption(beta.id);
    await settings.locator('.library-sides > div').nth(1).getByRole('button',{name:'Load into match',exact:true}).click();
    await expect.poll(()=>h.state().redTeam.id).toBe(beta.id);
    await page.reload();await page.getByRole('button',{name:'Match settings',exact:true}).click();
    await expect(page.getByLabel('Player 1',{exact:true}).first()).toHaveValue('Temporary Sub');
    await h.send({type:'draft_action',team:'blue',action:'ban',heroId:64});
    await request.put('/api/team-presets/'+id,{headers,data:{...teams[0],substitutes:[{...teams[0].substitutes[0],name:'Late Sub',role:'mid'}]}});
    await settings.getByRole('button',{name:'Refresh library',exact:true}).click();
    await expect(quick.getByLabel('Choose saved player',{exact:true})).toContainText('Late Sub');
    await quick.getByLabel('Choose saved player',{exact:true}).selectOption(teams[0].substitutes[0].id);
    await quick.getByRole('button',{name:'Fill player details',exact:true}).click();
    await settings.getByRole('button',{name:'Save settings',exact:true}).click();
    await expect.poll(()=>h.state().currentPhase).toBe(1);
    await expect.poll(()=>h.state().blueTeam.players[0]).toBe('Late Sub');
    expect(h.state().blueTeam.playerRoles[0]).toBe('mid');
    expect(h.state().blueTeam.playerPortraits[0]).toBe(teams[0].substitutes[0].portrait);
    await page.getByRole('button',{name:'Manage saved teams',exact:true}).click();
    await manager.getByLabel('Search teams',{exact:true}).fill('Alpha');
    await manager.getByRole('button',{name:'Alpha Library',exact:true}).click();
    await page.bringToFront();await page.screenshot({path:'artifacts/v23-team-library.png'});
    await manager.getByRole('button',{name:'Delete saved team',exact:true}).click();
    await expect(manager.locator('.library-status')).toContainText('Team deleted');
    expect(h.state().blueTeam.id).toBe(id);expect((await request.get(portrait)).status()).toBe(200);
    await manager.getByRole('button',{name:'Close team library',exact:true}).click();
    const redQuick=settings.locator('.quick-substitution').nth(1);
    await redQuick.getByLabel('Roster source',{exact:true}).selectOption(beta.id);
    await settings.getByLabel('Interface language',{exact:true}).selectOption('zh');
    await settings.getByRole('button',{name:'Save settings',exact:true}).click();
    await expect(settings.getByRole('button',{name:'管理队伍资料',exact:true})).toBeVisible();
  }finally{h.close();}
});

test('manual active match recalls a reserve without replacing team identity or other slots', async ({page,request,baseURL}) => {
  const h=await harness(baseURL),headers={Authorization:'Bearer e2e-control'};
  try {
    await h.send({type:'reset_match'});await h.send({type:'settings',settings:{...h.state(),language:'eng'}});
    const id=h.state().blueTeam.id;
    const saved=await (await request.post('/api/team-presets',{headers,data:{...initialState().blueTeam,name:'Reserve Source',substitutes:[{id:crypto.randomUUID(),name:'Relief',role:'mid',portrait:'/bench.png'}]}})).json();
    await h.send({type:'draft_action',team:'blue',action:'ban',heroId:64});
    page.on('dialog',dialog=>dialog.accept());
    await page.goto('/control#token=e2e-control');await page.getByRole('button',{name:'Match settings',exact:true}).click();
    const quick=page.locator('.quick-substitution').first();
    await quick.getByLabel('Roster source',{exact:true}).selectOption(saved.id);
    await quick.getByLabel('Choose saved player',{exact:true}).selectOption(saved.substitutes[0].id);
    await quick.getByLabel('Replace slot',{exact:true}).selectOption('2');
    await quick.getByRole('button',{name:'Fill player details',exact:true}).click();
    await page.bringToFront();await page.screenshot({path:'artifacts/v23-quick-substitution.png'});
    await page.getByRole('button',{name:'Save settings',exact:true}).click();
    await expect.poll(()=>h.state().blueTeam.players[2]).toBe('Relief');
    expect(h.state().blueTeam.id).toBe(id);expect(h.state().currentPhase).toBe(1);
    expect(h.state().blueTeam.players[0]).toBe('');expect(h.state().blueTeam.playerRoles[2]).toBe('mid');
    expect(h.state().blueTeam.playerPortraits[2]).toBe('/bench.png');
  }finally{h.close();}
});
