import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const root = new URL('../', import.meta.url);
const version = process.argv[2] || '16.19.1';
if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error('Expected Data Dragon version, e.g. 16.19.1');
async function get(url, binary = false) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${response.status}: ${url}`);
  return binary ? Buffer.from(await response.arrayBuffer()) : response.json();
}
const base = `https://ddragon.leagueoflegends.com/cdn/${version}`;
const [en, zh] = await Promise.all(['en_US', 'zh_CN'].map(locale => get(`${base}/data/${locale}/champion.json`)));
// Curated starting positions, not Riot role tags or current-patch pick-rate claims.
// Flex positions can be edited from the existing hero-data editor.
const positions = {
  'Mid Lane': 'Annie Galio TwistedFate Leblanc Vladimir Ryze Anivia Kassadin Veigar Swain Katarina Orianna Brand Cassiopeia Heimerdinger Akali Malzahar Lux Xerath Ahri Fizz Viktor Lissandra Syndra AurelionSol Zoe Yasuo Taliyah Akshan Zed Qiyana Azir Vex Yone Mel Locke Hwei',
  'Top Lane': 'Aatrox Ambessa Aurora Camille Chogath Darius DrMundo Fiora Gangplank Garen Gnar Gragas Gwen Illaoi Irelia Jax Jayce KSante Kayle Kennen Kled Malphite Mordekaiser Nasus Olaf Ornn Pantheon Poppy Quinn Renekton Riven Rumble Sett Shen Singed Sion Teemo Tryndamere Urgot Vayne Volibear MonkeyKing Yorick Zaahen',
  Jungle: 'Amumu Belveth Briar Diana Ekko Elise Evelynn Fiddlesticks Graves Hecarim Ivern JarvanIV Karthus Kayn Khazix Kindred LeeSin Lillia MasterYi Naafiri Nidalee Nocturne Nunu Rammus RekSai Rengar Sejuani Shaco Shyvana Skarner Sylas Talon Trundle Udyr Vi Viego Warwick XinZhao Zac',
  'Bot Lane': 'Aphelios Ashe Caitlyn Corki Draven Ezreal Jhin Jinx Kaisa Kalista KogMaw Lucian MissFortune Nilah Samira Senna Sivir Smolder Tristana Twitch Varus Xayah Yunara Zeri Ziggs',
  Support: 'Alistar Bard Blitzcrank Braum Janna Karma Leona Lulu Maokai Milio Morgana Nami Nautilus Neeko Pyke Rakan Rell Renata Seraphine Sona Soraka TahmKench Taric Thresh Velkoz Yuumi Zilean Zyra',
};
const lane = id => {
  const result = Object.entries(positions).find(([, ids]) => ids.split(' ').includes(id))?.[0];
  if (!result) throw new Error(`Review the starting position for new champion: ${id}`);
  return result;
};
// Validate the full position map before changing any local assets.
Object.values(en.data).forEach(champion => lane(champion.id));
await mkdir(new URL('public/champions/', root), { recursive: true });
const heroes = [];
const entries = Object.values(en.data).sort((a,b) => Number(a.key)-Number(b.key));
for (let i = 0; i < entries.length; i += 8) {
  heroes.push(...await Promise.all(entries.slice(i,i+8).map(async champion => {
    const imageLink = `/champions/${champion.id}.png`;
    await writeFile(new URL(`public${imageLink}`, root), await get(`${base}/img/champion/${champion.image.full}`, true));
    return { id: Number(champion.key), englishName: champion.name, chineseName: zh.data[champion.id].title,
      imageLink, artLink: `https://ddragon.leagueoflegends.com/cdn/img/champion/loading/${champion.id}_0.jpg`,
      occupation: lane(champion.id), altOccupation: '', aliases: [champion.id, champion.title, zh.data[champion.id].name] };
  })));
}
await writeFile(new URL('src/data/lolHeroes.ts', root), `// Riot Data Dragon ${version}; generated by scripts/lol-sync.mjs.\nimport type { Hero } from './heroTypes.js';\nconst heroes: Hero[] = ${JSON.stringify(heroes,null,2)};\nexport default heroes;\n`);
await writeFile(new URL('src/components/HeroList.tsx', root), "export { default } from '../data/lolHeroes.js';\n");
console.log(`Saved ${heroes.length} champions and local portraits from Data Dragon ${version} to ${fileURLToPath(root)}`);
